import { ArrowLeft, Check, ChevronDown, Network } from "lucide-react";
import { useState } from "react";
import { MarketingLogo, SectionTitle } from "./MarketingBrand";

const plans=[{name:"البداية",desc:"لاختبار المنصة وتجهيز أول قناة ووكيل.",items:["مساحة عمل واحدة","صندوق وارد موحد","وكيل ذكي أساسي","دعم الإعداد"]},{name:"النمو",desc:"للأنشطة التي تدير محادثات يومية وفريقًا صغيرًا.",hot:true,items:["وكلاء وقنوات أكثر","أتمتة وتوزيع متقدم","تقارير وتحليلات","دعم أولوية"]},{name:"الأعمال",desc:"للفرق الأكبر والاحتياجات المخصصة.",items:["صلاحيات متقدمة","تكاملات مخصصة","حدود تشغيل موسعة","إعداد ومتابعة مخصصة"]}];
const questions=[["هل أحتاج خبرة تقنية؟","لا. صُممت رحلة الإعداد لتكون واضحة، ويمكن ربط القنوات وضبط الوكيل من داخل المنصة خطوة بخطوة."],["هل يحل الوكيل مكان الموظف بالكامل؟","الوكيل يتولى الأعمال المتكررة والردود الأولية، بينما يبقى التحويل للموظف متاحًا حسب قواعدك."],["هل يمكن استخدام رقم واتساب قائم؟","تدعم المنصة مسارات الربط المتاحة من ميتا، بما فيها ربط رقم جديد أو التعايش عندما يكون مؤهلًا."],["هل بيانات الأنشطة مختلطة؟","لا. كل مساحة عمل معزولة، وتوجد صلاحيات وسجل تدقيق لمتابعة الإجراءات المهمة."]];

export default function MarketingClosing(){const[open,setOpen]=useState(0);return <>
<section id="pricing" className="wp-section py-24"><div className="wp-container wp-reveal"><SectionTitle eyebrow="الأسعار" title="ابدأ صغيرًا وتوسع عندما تنمو محادثاتك" description="اختر نقطة البداية المناسبة، ويمكن ترقية المساحة لاحقًا دون نقل البيانات أو إعادة الإعداد."/><div className="mt-12 grid gap-5 lg:grid-cols-3">{plans.map(p=><article key={p.name} className={`wp-glass relative rounded-[30px] p-7 ${p.hot?"border-blue-400/50":""}`}>{p.hot&&<span className="absolute -top-3 right-7 rounded-full bg-gradient-to-r from-blue-600 to-cyan-400 px-4 py-1.5 text-[10px] font-black text-white">الأنسب للنمو</span>}<h3 className="text-2xl font-black">{p.name}</h3><p className="wp-soft mt-3 min-h-[56px] text-sm leading-7">{p.desc}</p><div className="my-6 border-t border-[var(--line)]"/><ul className="space-y-3">{p.items.map(x=><li key={x} className="flex items-center gap-3 text-sm"><span className="grid h-5 w-5 place-items-center rounded-full bg-emerald-500/15 text-emerald-400"><Check className="h-3 w-3"/></span>{x}</li>)}</ul><a href="/register" className={`${p.hot?"wp-primary":"wp-secondary"} mt-7 flex h-12 items-center justify-center rounded-xl text-sm font-black transition`}>{p.name==="الأعمال"?"تواصل معنا":"ابدأ التجربة"}</a></article>)}</div></div></section>
<section id="faq" className="py-24"><div className="wp-container wp-reveal grid gap-10 lg:grid-cols-[.8fr_1.2fr]"><SectionTitle center={false} eyebrow="الأسئلة الشائعة" title="إجابات واضحة قبل أن تبدأ" description="أهم ما تحتاج معرفته عن طريقة العمل والربط والتحكم بالوكلاء."/><div className="space-y-3">{questions.map(([q,a],i)=><button key={q} type="button" onClick={()=>setOpen(open===i?-1:i)} className="wp-glass w-full rounded-2xl p-5 text-right"><span className="flex items-center justify-between gap-4"><strong className="text-sm sm:text-base">{q}</strong><ChevronDown className={`h-4 w-4 transition ${open===i?"rotate-180":""}`}/></span>{open===i&&<span className="wp-soft mt-4 block text-sm leading-7">{a}</span>}</button>)}</div></div></section>
<section className="pb-24"><div className="wp-container wp-reveal"><div className="relative overflow-hidden rounded-[36px] border border-blue-400/25 bg-gradient-to-br from-blue-700 via-blue-600 to-cyan-500 p-8 text-white sm:p-12"><div className="absolute -left-20 -top-28 h-72 w-72 rounded-full bg-white/20 blur-3xl"/><div className="relative grid items-center gap-8 lg:grid-cols-[1fr_auto]"><div><div className="inline-flex items-center gap-2 rounded-full border border-white/20 bg-white/10 px-4 py-2 text-xs font-black"><Network className="h-4 w-4"/>كل قنواتك وفريقك ووكلائك في مكان واحد</div><h2 className="mt-5 max-w-3xl text-3xl font-black leading-tight sm:text-5xl">حوّل المحادثات المبعثرة إلى عمل منظم ينمو.</h2><p className="mt-4 text-sm text-blue-50">أنشئ حسابك مجانًا وابدأ الإعداد دون بطاقة دفع أو خبرة تقنية.</p></div><a href="/register" className="inline-flex h-14 items-center justify-center gap-2 rounded-2xl bg-white px-7 text-sm font-black text-blue-700 shadow-xl">ابدأ مجانًا <ArrowLeft className="h-4 w-4"/></a></div></div></div></section>
<footer className="wp-section py-12"><div className="wp-container grid gap-9 md:grid-cols-[1.4fr_.7fr_.7fr_1fr]"><div><MarketingLogo/><p className="wp-soft mt-4 max-w-sm text-sm leading-7">منصة عربية موحّدة لإدارة محادثات العملاء وتشغيل وكلاء الذكاء الاصطناعي مع فريقك.</p></div><Links title="المنتج" items={[["المنصة","#platform"],["المزايا","#features"],["الأسعار","#pricing"]]}/><Links title="الشركة" items={[["من نحن","/about"],["تواصل معنا","/contact"],["الخصوصية","/privacy"]]}/><div><strong className="text-sm">التواصل</strong><div className="wp-soft mt-4 grid gap-3 text-xs"><a href="mailto:support@wesal.one" dir="ltr">support@wesal.one</a><span dir="ltr">+967 775 324 950</span><span>صنعاء، اليمن</span></div></div></div><div className="wp-container mt-10 flex flex-col justify-between gap-3 border-t border-[var(--line)] pt-6 text-[11px] text-[var(--mute)] sm:flex-row"><span>© 2026 وصال ون. جميع الحقوق محفوظة.</span><span className="flex gap-4"><a href="/privacy">سياسة الخصوصية</a><a href="/terms">شروط الاستخدام</a></span></div></footer>
</>}
function Links({title,items}:{title:string;items:string[][]}){return <div><strong className="text-sm">{title}</strong><div className="wp-soft mt-4 grid gap-3 text-xs">{items.map(([label,href])=><a key={href} href={href}>{label}</a>)}</div></div>}
