import { ArrowLeft, Check, Clock3, Languages, MessageCircle, Play, Zap } from "lucide-react";
import type { LucideIcon } from "lucide-react";
import AgentsHologram from "./AgentsHologram";
import { ChannelBadge, HeroCard, MarketingTag } from "./MarketingBrand";

const heroStats:Array<[LucideIcon,string,string]>=[[Clock3,"24/7","أداء مستمر"],[MessageCircle,"موحّد","كل محادثاتك"],[Zap,"دقائق","بدء الربط"],[Languages,"عربي","تجربة RTL"]];

export default function MarketingHero(){return <section id="home" className="relative min-h-[720px] overflow-hidden py-14 lg:py-16"><div className="wp-grid pointer-events-none absolute inset-0 opacity-45 [mask-image:radial-gradient(ellipse_90%_75%_at_50%_42%,#000_28%,transparent_82%)]"/><div className="pointer-events-none absolute -right-48 -top-48 h-[620px] w-[620px] rounded-full bg-[radial-gradient(circle,rgba(46,109,255,.34),transparent_70%)] blur-3xl"/><div className="wp-container relative grid items-center gap-10 lg:grid-cols-[1.05fr_.92fr_1.08fr]">
  <div className="order-1 text-center lg:order-3 lg:text-right"><MarketingTag>منصة ذكاء اصطناعي لإدارة أعمالك ونموّك</MarketingTag><h1 className="mt-7 text-[42px] font-black leading-[1.18] sm:text-5xl lg:text-[58px]">وكلاء ذكاء اصطناعي<br/>يديرون <span className="wp-gradient">أعمالك</span><br/>باحتراف</h1><p className="wp-soft mx-auto mt-6 max-w-xl text-sm leading-8 sm:text-base lg:mx-0">وصال ون تجمع تواصل العملاء وخدمة الفريق في مكان واحد. ابدأ الربط والتشغيل خلال دقائق، واترك للوكلاء الأذكياء الرد والقيادة والمتابعة بينما تظل أنت المتحكم.</p><div className="mt-7 flex flex-wrap justify-center gap-3 lg:justify-start"><a href="/register" className="wp-primary inline-flex h-12 items-center gap-2 rounded-xl px-6 text-sm font-black transition">ابدأ الآن <ArrowLeft className="h-4 w-4"/></a><a href="#platform" className="wp-secondary inline-flex h-12 items-center gap-2 rounded-xl px-5 text-sm font-black transition"><Play className="h-4 w-4"/> شاهد كيف تعمل</a></div><div className="wp-mute mt-4 flex flex-wrap justify-center gap-x-5 gap-y-2 text-[11px] font-bold lg:justify-start">{["تجربة مجانية","دون بطاقة دفع","إعداد بلا تعقيد"].map(x=><span key={x} className="flex items-center gap-1.5"><Check className="h-3.5 w-3.5 text-cyan-400"/>{x}</span>)}</div></div>
  <div className="order-2 relative mx-auto w-full max-w-[440px] lg:order-2"><div className="absolute -inset-16 bg-[radial-gradient(circle,rgba(38,105,255,.42),rgba(21,191,224,.13)_42%,transparent_72%)] blur-2xl"/><div className="wp-spin absolute left-1/2 top-1/2 aspect-square w-[112%] -translate-x-1/2 -translate-y-1/2 rounded-full border border-blue-400/20"><span className="absolute left-1/2 top-0 h-2.5 w-2.5 -translate-x-1/2 -translate-y-1/2 rounded-full bg-cyan-300 shadow-[0_0_18px_#20d8ee]"/></div><AgentsHologram/><div className="wp-glass absolute bottom-3 left-1/2 z-20 flex -translate-x-1/2 items-center gap-2 rounded-full px-4 py-2 text-[11px] font-black whitespace-nowrap"><span className="h-2 w-2 rounded-full bg-emerald-400 shadow-[0_0_10px_#34d399]"/>الوكلاء يعملون الآن 24/7</div></div>
  <div className="order-3 grid gap-4 sm:grid-cols-2 lg:order-1 lg:grid-cols-1"><HeroCard title="منصة أعمال متصلة" className="wp-float"><div className="flex flex-wrap gap-2"><ChannelBadge name="W" label="واتساب" color="#24c968"/><ChannelBadge name="I" label="إنستغرام" color="linear-gradient(135deg,#f58529,#dd2a7b,#515bd4)"/><ChannelBadge name="M" label="ماسنجر" color="#168aff"/></div><p className="wp-mute mt-3 text-[11px] leading-5">إدارة المحادثات والعمليات من نافذة واحدة.</p></HeroCard><HeroCard title="صندوق وارد موحّد"><div className="space-y-3">{[["شركة النور","استفسار العميل بنجاح","2m"],["متجر القمة","تم إنشاء طلب جديد","5m"],["مؤسسة الرؤية","تحويل إلى الموظف","7m"]].map(([name,text,time],i)=><div key={name} className="flex items-center gap-2"><span className="grid h-8 w-8 place-items-center rounded-xl text-[10px] font-black text-white" style={{background:["#25d366","#e34a81","#238cff"][i]}}>{name[0]}</span><span className="min-w-0 flex-1"><strong className="block truncate text-[11px]">{name}</strong><span className="wp-mute block truncate text-[10px]">{text}</span></span><span className="wp-mute text-[9px]">{time}</span></div>)}</div></HeroCard><HeroCard title="أداء الوكلاء" className="hidden lg:block"><div className="flex items-end gap-4"><div className="grid h-16 w-16 place-items-center rounded-full border-[7px] border-blue-500/30 text-sm font-black">96%</div><div className="flex h-16 flex-1 items-end gap-1">{[30,44,38,59,54,72,86].map((h,i)=><span key={i} className="flex-1 rounded-t bg-gradient-to-t from-blue-600 to-cyan-300" style={{height:`${h}%`}}/>)}</div></div></HeroCard></div>
</div><div className="wp-container mt-12"><div className="wp-glass grid overflow-hidden rounded-[28px] sm:grid-cols-2 lg:grid-cols-4">{heroStats.map(([Icon,value,label],i)=><div key={label} className={`flex items-center justify-center gap-4 px-5 py-6 ${i?"border-t border-[var(--line)] sm:border-r sm:border-t-0":""}`}><span className="grid h-11 w-11 place-items-center rounded-2xl border border-blue-400/20 bg-blue-500/10 text-cyan-300"><Icon className="h-5 w-5"/></span><span><strong className="block text-2xl font-black">{value}</strong><span className="wp-mute text-xs font-bold">{label}</span></span></div>)}</div></div></section>}
