import { BarChart3, Bot, Inbox, Users, Workflow, ArrowLeft } from "lucide-react";
import type { LucideIcon } from "lucide-react";
import { MarketingLogo, SectionTitle } from "./MarketingBrand";

const sidebar: Array<[LucideIcon,string]>=[[Inbox,"الوارد"],[Bot,"الوكلاء"],[Users,"العملاء"],[Workflow,"الأتمتة"],[BarChart3,"التحليلات"]];

export default function MarketingPlatform(){return <section id="platform" className="wp-section py-24"><div className="wp-container wp-reveal"><SectionTitle eyebrow="المنصة" title="كل ما تحتاجه لإدارة المحادثة من أول رسالة إلى نتيجة" description="واجهة عربية موحّدة تجمع العميل، المحادثة، الوكيل، الموظف، الطلب، والمتابعة دون القفز بين أدوات متفرقة."/><div className="wp-glass relative mt-12 overflow-hidden rounded-[30px] p-3 sm:p-5"><div className="mb-4 flex items-center gap-2 border-b border-[var(--line)] pb-4"><span className="h-2.5 w-2.5 rounded-full bg-red-400"/><span className="h-2.5 w-2.5 rounded-full bg-amber-300"/><span className="h-2.5 w-2.5 rounded-full bg-emerald-400"/><span className="wp-mute ms-3 text-[10px]">app.wesal.one/inbox</span></div><div className="grid min-h-[430px] gap-3 lg:grid-cols-[175px_235px_1fr_210px]">
  <aside className="rounded-2xl border border-[var(--line)] bg-white/[.025] p-4"><MarketingLogo compact/><div className="mt-7 space-y-2">{sidebar.map(([Icon,label],i)=><div key={label} className={`flex items-center gap-3 rounded-xl px-3 py-2.5 text-xs font-bold ${i===0?"bg-blue-500/15 text-cyan-300":"wp-soft"}`}><Icon className="h-4 w-4"/>{label}</div>)}</div></aside>
  <div className="rounded-2xl border border-[var(--line)] bg-white/[.025] p-3"><div className="flex items-center justify-between"><strong className="text-sm">المحادثات</strong><span className="rounded-full bg-blue-500/15 px-2 py-1 text-[9px] font-black text-cyan-300">12 جديدة</span></div><div className="mt-4 space-y-2">{["شركة النور","متجر القمة","مؤسسة أفق","سارة محمد","مركز الريادة"].map((name,i)=><div key={name} className={`rounded-xl border p-3 ${i===0?"border-blue-400/30 bg-blue-500/10":"border-[var(--line)]"}`}><div className="flex items-center gap-2"><span className="grid h-8 w-8 place-items-center rounded-xl bg-gradient-to-br from-blue-500 to-cyan-400 text-xs font-black text-white">{name[0]}</span><span className="min-w-0 flex-1"><strong className="block text-[11px]">{name}</strong><span className="wp-mute block truncate text-[9px]">أرغب بمعرفة تفاصيل الخدمة...</span></span><span className="wp-mute text-[9px]">{i+2}m</span></div></div>)}</div></div>
  <div className="flex flex-col rounded-2xl border border-[var(--line)] bg-white/[.025] p-4"><div className="flex items-center gap-3 border-b border-[var(--line)] pb-3"><span className="grid h-9 w-9 place-items-center rounded-xl bg-emerald-500 text-xs font-black text-white">ن</span><span><strong className="block text-xs">شركة النور</strong><span className="text-[9px] font-bold text-emerald-400">متصل الآن</span></span></div><div className="flex-1 space-y-3 py-6"><div className="ms-auto max-w-[80%] rounded-2xl rounded-bl-md bg-blue-600 px-4 py-3 text-xs leading-6 text-white">أهلاً بك 👋 كيف أقدر أخدمك اليوم؟</div><div className="max-w-[82%] rounded-2xl rounded-br-md bg-white/[.07] px-4 py-3 text-xs leading-6">أريد ربط واتساب وإنستغرام والرد على العملاء تلقائيًا.</div><div className="ms-auto max-w-[86%] rounded-2xl rounded-bl-md bg-blue-600 px-4 py-3 text-xs leading-6 text-white">ممتاز. وصال ون تجمع القنوات وتتيح لك وكيلًا ذكيًا مع تحويل فوري للموظف.</div></div><div className="flex gap-2"><div className="wp-soft flex-1 rounded-xl border border-[var(--line)] px-3 py-3 text-[10px]">اكتب رسالة...</div><button className="grid h-10 w-10 place-items-center rounded-xl bg-blue-600 text-white"><ArrowLeft className="h-4 w-4"/></button></div></div>
  <aside className="rounded-2xl border border-[var(--line)] bg-white/[.025] p-4"><strong className="text-sm">تفاصيل العميل</strong><div className="mt-5 grid place-items-center"><span className="grid h-16 w-16 place-items-center rounded-2xl bg-gradient-to-br from-blue-500 to-cyan-400 text-xl font-black text-white">ن</span><strong className="mt-3 text-sm">شركة النور</strong><span className="wp-mute mt-1 text-[10px]">عميل محتمل</span></div><div className="mt-6 space-y-3 text-[10px]"><div className="flex justify-between"><span className="wp-mute">القناة</span><strong>واتساب</strong></div><div className="flex justify-between"><span className="wp-mute">المسؤول</span><strong>الوكيل الذكي</strong></div><div className="flex justify-between"><span className="wp-mute">الحالة</span><strong className="text-emerald-400">مفتوحة</strong></div></div><button className="wp-secondary mt-6 w-full rounded-xl py-2.5 text-[10px] font-black">فتح ملف العميل</button></aside>
</div></div></div></section>}
