import { ArrowLeft, BarChart3, Bot, Check, Headphones, Inbox, ShieldCheck, Users, Workflow } from "lucide-react";
import { SectionTitle } from "./MarketingBrand";

const features=[[Inbox,"صندوق وارد موحّد","واتساب وإنستغرام وماسنجر وقنواتك الأخرى في مكان واحد مرتب."],[Bot,"وكلاء أذكياء","وكلاء يجيبون، يفهمون النية، وينفذون مهام العمل طوال اليوم."],[Users,"تحويل للبشري","يتوقف الوكيل عندما يتولى الموظف المحادثة ويعود وفق قواعد واضحة."],[Workflow,"أتمتة المهام","توزيع ومتابعة وتذكير وتحديث للحالات دون عمل يدوي متكرر."],[BarChart3,"تحليلات مفهومة","تابع سرعة الرد والمحادثات والفرص وأداء الفريق من لوحة واحدة."],[ShieldCheck,"أمان وعزل","بيانات كل مساحة عمل معزولة مع صلاحيات وسجل تدقيق للإجراءات."]] as const;
const steps=[["01","أنشئ مساحة عملك","سجّل خلال دقيقة، دون بطاقة دفع."],["02","اربط قنواتك","خطوات واضحة لربط حسابات ميتا وقنوات التواصل."],["03","جهّز الوكيل","أضف معرفة نشاطك وقواعد الرد والتصعيد."],["04","ابدأ وراقب","دع الوكلاء يعملون وتدخل أنت فقط عند الحاجة."]] as const;

export default function MarketingFeatures(){return <>
<section id="features" className="py-24"><div className="wp-container wp-reveal"><SectionTitle eyebrow="المزايا" title="وكلاء يعملون مع فريقك، لا بعيدًا عنه" description="صممنا التجربة لتقلل الأعمال المتكررة وتحافظ على قرار الإنسان عندما تصبح المحادثة حساسة أو تحتاج خبرة."/><div className="mt-12 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{features.map(([Icon,title,text],i)=><article key={title} className="wp-glass rounded-3xl p-6 transition hover:-translate-y-1 hover:border-blue-400/35"><div className="flex items-start justify-between"><span className="grid h-12 w-12 place-items-center rounded-2xl bg-gradient-to-br from-blue-600/25 to-cyan-400/10 text-cyan-300"><Icon className="h-5 w-5"/></span><span className="wp-mute text-xs font-black">0{i+1}</span></div><h3 className="mt-5 text-lg font-black">{title}</h3><p className="wp-soft mt-3 text-sm leading-7">{text}</p></article>)}</div></div></section>
<section id="how" className="wp-section py-24"><div className="wp-container wp-reveal"><SectionTitle eyebrow="كيف تبدأ" title="من التسجيل إلى أول وكيل يعمل بأربع خطوات" description="رحلة واضحة ومباشرة، بدون تثبيت أنظمة معقدة أو الحاجة إلى فريق تقني داخلي."/><div className="relative mt-14 grid gap-4 lg:grid-cols-4">{steps.map(([n,title,text],i)=><div key={n} className="wp-glass relative rounded-3xl p-6"><span className="wp-gradient text-3xl font-black">{n}</span><h3 className="mt-5 text-lg font-black">{title}</h3><p className="wp-soft mt-3 text-sm leading-7">{text}</p>{i<3&&<ArrowLeft className="absolute -left-3 top-1/2 hidden h-5 w-5 text-blue-400 lg:block"/>}</div>)}</div></div></section>
<section className="py-24"><div className="wp-container wp-reveal grid items-center gap-10 lg:grid-cols-2"><div><SectionTitle center={false} eyebrow="التحكم البشري" title="الذكاء الاصطناعي يسرّع العمل، وفريقك يبقى صاحب القرار" description="حدّد متى يجيب الوكيل، ومتى يتوقف، ومن يتولى المحادثة. كل عملية واضحة وقابلة للمراجعة."/><div className="mt-7 grid gap-3 sm:grid-cols-2">{["إيقاف تلقائي عند تدخل الموظف","توزيع حسب الفريق أو المهارة","سجل أحداث وتدقيق","قواعد تصعيد قابلة للتخصيص"].map(x=><div key={x} className="flex items-center gap-3 rounded-2xl border border-[var(--line)] bg-white/[.025] p-4 text-xs font-bold"><span className="grid h-6 w-6 place-items-center rounded-full bg-emerald-500/15 text-emerald-400"><Check className="h-3.5 w-3.5"/></span>{x}</div>)}</div></div><div className="wp-glass rounded-[30px] p-5"><div className="rounded-2xl border border-[var(--line)] bg-white/[.025] p-4"><div className="flex items-center justify-between"><span><strong className="block text-sm">حالة المحادثة</strong><span className="wp-mute text-[10px]">شركة النور · واتساب</span></span><span className="rounded-full bg-amber-500/15 px-3 py-1.5 text-[10px] font-black text-amber-300">تدخل بشري</span></div><div className="mt-6 space-y-3"><Message icon={<Bot/>} title="الوكيل الذكي" text="جمعت تفاصيل الطلب وحددت أن العميل يحتاج موافقة خاصة."/><Message icon={<Headphones/>} title="أحمد · فريق المبيعات" text="استلم المحادثة. تم إيقاف ردود الوكيل مؤقتًا لمنع التداخل." human/></div></div></div></div></section>
</>}
function Message({icon,title,text,human=false}:{icon:React.ReactNode;title:string;text:string;human?:boolean}){return <div className="flex gap-3"><span className={`grid h-9 w-9 place-items-center rounded-xl [&>svg]:h-4 [&>svg]:w-4 ${human?"bg-cyan-500/15 text-cyan-300":"bg-blue-500/15 text-blue-300"}`}>{icon}</span><div className={`flex-1 rounded-2xl border p-3 ${human?"border-cyan-400/25 bg-cyan-400/[.06]":"border-[var(--line)]"}`}><strong className="text-[10px]">{title}</strong><p className="wp-soft mt-2 text-xs leading-6">{text}</p></div></div>}
