import { useEffect, useState } from "react";
import { Menu, Moon, Sun, X } from "lucide-react";
import "@/styles/wesal-marketing.css";
import { MarketingLogo } from "./MarketingBrand";
import MarketingHero from "./MarketingHero";
import MarketingPlatform from "./MarketingPlatform";
import MarketingFeatures from "./MarketingFeatures";
import MarketingClosing from "./MarketingClosing";

export default function WesalMarketingPage(){const[dark,setDark]=useState(()=>typeof window==="undefined"||localStorage.getItem("wesal-theme")!=="light");const[menu,setMenu]=useState(false);useEffect(()=>{localStorage.setItem("wesal-theme",dark?"dark":"light")},[dark]);useEffect(()=>{const io=new IntersectionObserver(es=>es.forEach(e=>e.isIntersecting&&e.target.classList.add("show")),{threshold:.12});document.querySelectorAll(".wesal-public .wp-reveal").forEach(e=>io.observe(e));return()=>io.disconnect()},[]);const links=[["المنصة","#platform"],["المزايا","#features"],["كيف تعمل","#how"],["الأسعار","#pricing"],["الأسئلة","#faq"]];return <div className={`wesal-public ${dark?"dark":"light"}`} dir="rtl"><header className="wp-nav sticky top-0 z-50 border-b"><div className="wp-container flex h-[74px] items-center justify-between gap-4"><a href="#home"><MarketingLogo compact/></a><nav className="hidden items-center gap-7 lg:flex">{links.map(([l,h])=><a key={h} href={h} className="wp-soft text-sm font-bold hover:text-[var(--fg)]">{l}</a>)}</nav><div className="flex items-center gap-2"><a href="/login" className="wp-secondary hidden h-10 items-center rounded-xl px-4 text-xs font-black sm:inline-flex">تسجيل الدخول</a><button type="button" onClick={()=>setDark(v=>!v)} className="wp-secondary grid h-10 w-10 place-items-center rounded-xl" aria-label="تغيير المظهر">{dark?<Moon className="h-4 w-4"/>:<Sun className="h-4 w-4"/>}</button><a href="/register" className="wp-primary hidden h-10 items-center rounded-xl px-5 text-xs font-black sm:inline-flex">ابدأ الآن</a><button type="button" onClick={()=>setMenu(v=>!v)} className="wp-secondary grid h-10 w-10 place-items-center rounded-xl lg:hidden">{menu?<X className="h-5 w-5"/>:<Menu className="h-5 w-5"/>}</button></div></div>{menu&&<div className="wp-container border-t border-[var(--line)] py-4 lg:hidden"><nav className="grid gap-1">{links.map(([l,h])=><a key={h} href={h} onClick={()=>setMenu(false)} className="wp-soft rounded-xl px-3 py-3 text-sm font-bold">{l}</a>)}<a href="/login" className="wp-soft rounded-xl px-3 py-3 text-sm font-bold">تسجيل الدخول</a><a href="/register" className="wp-primary mt-2 rounded-xl px-4 py-3 text-center text-sm font-black">ابدأ الآن</a></nav></div>}</header><main><MarketingHero/><MarketingPlatform/><MarketingFeatures/><MarketingClosing/></main></div>}
