import { describe, expect, test } from "vitest"
import { decodeButtonPayload, encodeButtonPayload } from "../src/util"

describe("decodeButtonPayload bare flow ID", () => {
  test("numeric payload with allowBareFlowId returns the flow ID", () => {
    expect(
      decodeButtonPayload("1783440960229", { allowBareFlowId: true }),
    ).toEqual({
      flowId: "1783440960229",
    })
  })

  test("numeric payload without allowBareFlowId is rejected", () => {
    expect(decodeButtonPayload("1783440960229")).toBeNull()
    expect(
      decodeButtonPayload("1783440960229", { allowBareFlowId: false }),
    ).toBeNull()
  })

  test("non-numeric payload with allowBareFlowId is rejected", () => {
    expect(decodeButtonPayload("abc123", { allowBareFlowId: true })).toBeNull()
    expect(
      decodeButtonPayload("123abc456", { allowBareFlowId: true }),
    ).toBeNull()
    expect(decodeButtonPayload("", { allowBareFlowId: true })).toBeNull()
  })

  test("numeric payload outside the snowflake length is rejected", () => {
    // 12 digits — below the minimum snowflake length
    expect(
      decodeButtonPayload("123456789012", { allowBareFlowId: true }),
    ).toBeNull()
    // 20 digits — beyond the maximum length
    expect(
      decodeButtonPayload("12345678901234567890", { allowBareFlowId: true }),
    ).toBeNull()
    // 17 digits — the length currently generated by createId
    expect(
      decodeButtonPayload("11612473309626368", { allowBareFlowId: true }),
    ).toEqual({ flowId: "11612473309626368" })
  })

  test("numeric payload above the signed bigint maximum is rejected", () => {
    // 19 digits, but greater than the signed bigint max 9223372036854775807
    expect(
      decodeButtonPayload("9999999999999999999", { allowBareFlowId: true }),
    ).toBeNull()
    // one past the max is rejected
    expect(
      decodeButtonPayload("9223372036854775808", { allowBareFlowId: true }),
    ).toBeNull()
    // exactly the max (and a smaller 19-digit value) is accepted
    expect(
      decodeButtonPayload("9223372036854775807", { allowBareFlowId: true }),
    ).toEqual({ flowId: "9223372036854775807" })
    expect(
      decodeButtonPayload("1000000000000000000", { allowBareFlowId: true }),
    ).toEqual({ flowId: "1000000000000000000" })
  })

  test("colon payload decodes the same with and without the flag", () => {
    const payload = "123:456:789"
    const expected = {
      flowId: "123",
      flowVersionId: "456",
      buttonId: "789",
    }
    expect(decodeButtonPayload(payload)).toEqual(expected)
    expect(decodeButtonPayload(payload, { allowBareFlowId: true })).toEqual(
      expected,
    )
  })

  test("legacy base64 payload decodes the same with and without the flag", () => {
    const payload = btoa(JSON.stringify({ f: "123", b: "789" }))
    const expected = { flowId: "123", buttonId: "789" }
    expect(decodeButtonPayload(payload)).toEqual(expected)
    expect(decodeButtonPayload(payload, { allowBareFlowId: true })).toEqual(
      expected,
    )
  })

  test("encode/decode round-trip still works", () => {
    const encoded = encodeButtonPayload({
      flowId: "123",
      flowVersionId: "456",
      buttonId: "789",
    })
    expect(decodeButtonPayload(encoded)).toEqual({
      flowId: "123",
      flowVersionId: "456",
      buttonId: "789",
    })
  })

  test("a colon segment that merely contains a digit is rejected, not just accepted because it has one", () => {
    // Security regression: a channel webhook (e.g. WhatsApp's button.payload)
    // is untrusted input. Before this schema required the WHOLE segment to be
    // digits, "x1:y1:z1" decoded successfully (each segment merely contained
    // a digit) and would crash downstream when bound to a bigint column.
    expect(decodeButtonPayload("x1:y1:z1")).toBeNull()
    expect(decodeButtonPayload("123:abc:789")).toBeNull()
    expect(decodeButtonPayload("123: :789")).toBeNull()
  })

  test("a colon segment that is all digits but exceeds the signed bigint range is rejected", () => {
    expect(decodeButtonPayload("9999999999999999999:456:789")).toBeNull()
  })
})
