import { decodeButtonPayload } from "@chatbotx.io/flow-config"
import { logger } from "../../lib/logger"

export type FlowActionKind = "postback" | "quickReply"

export type FlowActionContext = {
  kind: FlowActionKind
  integrationType: string
  integrationIdentifier: string
}

/**
 * Meta can deliver button payloads that were not generated by this flow engine:
 * another app connected to the same page, native ice breakers, or old formats.
 * Treat those as plain messages so the automated-response path can still run.
 */
export const sanitizeFlowAction = (
  raw: string | null,
  context: FlowActionContext,
): string | null => {
  if (!raw) {
    return null
  }

  if (decodeButtonPayload(raw) !== null) {
    return raw
  }

  logger.warn(
    { ...context, action: raw },
    "Dropping undecodable flow action from channel webhook",
  )

  return null
}
