import { Router, type IRouter } from "express";
import healthRouter from "./health";
import webhookMetaRouter from "../modules/webhooks/meta.routes";
import authRouter from "../modules/auth/auth.routes";
import workspaceRouter from "../modules/workspace/workspace.routes";
import usersRouter from "../modules/users/users.routes";
import auditRouter from "../modules/audit/audit.routes";
import contactsRouter from "../modules/contacts/contacts.routes";
import conversationsRouter from "../modules/conversations/conversations.routes";
import ticketsRouter from "../modules/tickets/tickets.routes";
import tasksRouter from "../modules/tasks/tasks.routes";
import followupsRouter from "../modules/followups/followups.routes";
import opportunitiesRouter from "../modules/opportunities/opportunities.routes";
import ordersRouter from "../modules/orders/orders.routes";
import paymentsRouter from "../modules/payments/payments.routes";
import paymentMethodsRouter from "../modules/payments/payment-methods.routes";
import exchangeRatesRouter from "../modules/payments/exchange-rates.routes";
import dashboardRouter from "../modules/dashboard/dashboard.routes";
import channelsRouter from "../modules/channels/channels.routes";
import debtsRouter from "../modules/debts/debts.routes";
import integrationsRouter from "../modules/integrations/integrations.routes";
import knowledgeRouter from "../modules/knowledge/knowledge.routes";
import aiRouter from "../modules/ai/ai.routes";
import approvalsRouter from "../modules/approvals/approvals.routes";
import analyticsRouter from "../modules/analytics/analytics.routes";
import reportsRouter from "../modules/reports/reports.routes";
import { apiLimiter } from "../lib/rateLimiter";
import { requireVerifiedEmail } from "../middlewares/requireVerifiedEmail";

const router: IRouter = Router();

router.use(healthRouter);
router.use("/webhooks", webhookMetaRouter);
router.use(apiLimiter);
router.use("/auth", authRouter);
router.use(requireVerifiedEmail);
router.use("/workspace", workspaceRouter);
router.use("/users", usersRouter);
router.use("/audit-logs", auditRouter);
router.use("/contacts", contactsRouter);
router.use("/conversations", conversationsRouter);
router.use("/tickets", ticketsRouter);
router.use("/tasks", tasksRouter);
router.use("/followups", followupsRouter);
router.use("/opportunities", opportunitiesRouter);
router.use("/orders", ordersRouter);
router.use("/payments", paymentsRouter);
router.use("/payment-methods", paymentMethodsRouter);
router.use("/exchange-rates", exchangeRatesRouter);
router.use("/dashboard", dashboardRouter);
router.use("/channels", channelsRouter);
router.use("/debts", debtsRouter);
router.use("/integrations", integrationsRouter);
router.use("/knowledge", knowledgeRouter);
router.use("/ai", aiRouter);
router.use("/approvals", approvalsRouter);
router.use("/analytics", analyticsRouter);
router.use("/reports", reportsRouter);

export default router;
