import z from "zod"

export const contactSources = z.enum([
  "inboundMessage",
  "webchat",
  "ads",
  "botLink",
  "chatPlugin",
  "comments",
  "imported",
  "api",
  "direct",
])
export type ContactSource = z.infer<typeof contactSources>

export const genderTypes = z.enum(["male", "female", "unknown"])
export type GenderType = z.infer<typeof genderTypes>

export const systemFieldTypes = z.enum([
  "first_name",
  "last_name",
  "full_name",
  "email",
  "phone",
  "user_country",
  "user_state",
  "user_city",
  "inbox_link",
  "gender",
  "locale",
  "language",
  "locale2",
  "ig_user_name",
  "ig_followers",
  "ig_verified",
  "ig_follow_business",
  "ig_business_follow_user",
  "profile_pic",
  "timezone",
  "timezone_name",
  "user_id",
  "subscribed_date",
  "fb_chat_link",
  "me",
  "user_code",
  "last_btn_title",
  "last_interaction",
  "last_order",
  "last_seen",
  "last_input",
  "last_input_type",
  "consecutive_failed_reply",
  "last_ref",
  "user_channel",
  "user_hash",
  "user_tags",
  "user_external_id",
  "user_source",
  "assigned_admin_name",
  "assigned_admin_email",
  "assigned_admin_id",
  "current_user_time",
  "chat_history",
  "chat_history_large",
  "chat_history_details",
  "chat_history_details_large",
  "ai.queued.messages",
  "user_notes",
  "last_user_note",
  "webchat",
  "webchat_parent_url",
  "avatar",

  "account_id",
  "account_name",
  "account_image",
  "api_key",

  "last_ad",
  "last_ctwa",
  "last_ad_source_url",
  "last_ad_source_platform",
  "last_fb_comment",
  "last_post_id",
  "last_comment_id",
  "total_new_tagged",
  "total_tagged",
  "last_latitude",
  "last_longitude",
  "last_error_log",
  "last_outbound_message_at",
  "last_commented_post_text",

  "last_step",
  "current_step",
  "booking_calendar",
  "booking_date",
  "booking_link",
  "member_name",
  "team_name",
  "last_input_failure",

  "workspace_id",
  "workspace_name",
  "current_time",
  "page_user_name",
  "wa_user_id",
  "wa_user_name",
])
export type SystemFieldType = z.infer<typeof systemFieldTypes>

export const reservedCustomFieldNames = z.enum([])
export type ReservedCustomFieldName = z.infer<typeof reservedCustomFieldNames>

export const fillableContactKeys = [
  "phoneNumber",
  "email",
  "firstName",
  "lastName",
  "gender",
  "timezone",
] as const
export type FillableContactKey = (typeof fillableContactKeys)[number]

/**
 * The atomic contact-info kinds a contact can hold: exactly one is touched per
 * change, so this is what the `contactInfoUpdated` trigger reports (which info
 * type was updated).
 */
export const contactInfoTypes = z.enum(["phone", "email"])
export type ContactInfoType = z.infer<typeof contactInfoTypes>

/**
 * Selectable values for the `hasContactInfo` filter. Extends the atomic
 * {@link contactInfoTypes} with the `phoneAndEmail` composite so a contact can
 * be required to have BOTH a phone and an email, not just either one.
 */
export const contactInfoFilterValues = z.enum([
  "phone",
  "email",
  "phoneAndEmail",
])
export type ContactInfoFilterValue = z.infer<typeof contactInfoFilterValues>

export const contactFilterFields = z.enum([
  "fullName",
  "country",
  "continent",
  "gender",
  "subscribedToBroadcast",
  "contactCreatedAt",
  "contactCreatedDateMinutesAgo",
  "source",
  "conversationTransferredToHuman",
  "interactedInLast24h",
  "followUp",
  "archived",
  "blocked",
  "existingContact",
  "isGuestUser",
  "currentChannel",
  "inbox",
  "subjectToEuRules",
  "timezone",
  "hasOpportunity",
  "hasOpenOpportunity",
  "hasWonOpportunity",
  "hasLostOpportunity",
  "instagramStoryReply",
  "followsBusinessOnInstagram",
  "businessFollowsUserOnInstagram",
  "verifiedAccountOnInstagram",
  "followerCountOnInstagram",
  "lastSent",
  "lastDelivered",
  "lastSeen",
  "lastSeenMinutesAgo",
  "lastInteraction",
  "lastInteractionMinutesAgo",
  "unreplied",
  "unread",
  "appliedJobs",
  "email",
  "phone",
  "hasContactInfo",
  "tags",
  "completedWhatsAppFlows",
  "messengerList",
  "subscribedToDripCampaign",
  "conversationAssigned",
  "entryPointsLinks",
  "sentMessage",
  "keywordsReceived",
  "customFields",
  "customField",
  "executedFlow",
  "executedStep",
  "consecutiveAiFailures",
  "questionnaireStarted",
  "questionnaireInProgress",
  "questionnaireFinished",
  "couponTopic",
  "votedOnPoll",
  "lastComment",
  "commentedOnPost",
  "reactedOnPost",
  "lastTotalTaggedUsers",
  "lastTotalNewTaggedUsers",
  "phoneWasVerified",
  "optedInForSms",
  "broadcastSent",
  "broadcastDelivered",
  "broadcastSeen",
  "broadcastClicked",
  "broadcastFailed",
  "emailWasVerified",
  "optedInForEmail",
  "emailSent",
  "emailDelivered",
  "emailOpened",
  "emailClicked",
  "isWithinWorkingHours",
  "currentDate",
  "currentTime",
  "currentDayOfMonth",
  "currentDayOfWeek",
  "currentMonth",
  "bought",
  "boughtItems",
  "totalSpent",
  "numberOfOrders",
  "shoppingCartTotal",
  "shoppingCartSubtotal",
  "shoppingCartIsEmpty",
  "shoppingCartContainsItems",
  "lastSentMessageFailed",
  "lastUserInput",
  "lastUserInputType",
  "locale",
  "language",
  "fromCtwaAd",
  "ctwaConversion",
  "ctwaRetarget",
])
export type ContactFilterField = z.infer<typeof contactFilterFields>
