import z from "zod"

export const triggerActions = z.enum([
  "startAnotherFlow",
  "startExternalStep",
  "addTag",
  "removeTag",
  "setCustomField",
  "clearCustomField",
  "transferConversationToHuman",
  "sendMetaCapiEvent",
  "runGoogleSheet",
  "archiveConversation",
  "unarchiveConversation",
  "assignConversation",
  "unassignConversation",
  "disableBot",
  "enableBot",
])
export type TriggerAction = z.infer<typeof triggerActions>

export const triggerEventTypes = z.enum([
  "tagApplied",
  "tagRemoved",
  "customFieldValueChanged",
  "contactInfoUpdated",
  "dateTimeBasedTrigger",
  "conversationTransferredToHuman",
  "conversationTransferredToBot",
  "newContact",
  "contactUnsubscribedFormBroadcast",
  "archived",
  "followUp",
  "conversationAssigned",
  "conversationUnassigned",
  "incomingCall",
  "missedAudioCall",
  "callEnded",
  "ticketCreated",
  "ticketMovedToStage",
  "ticketValueChanged",
  "ticketStatusChanged",
  "ticketPriorityChanged",
  "subscribedToSequence",
  "unsubscribedFromSequence",
  "WhatsappShoppingCartSent",
  "userAskedAboutProduct",
  "cartAbandoned",
  "newOrder",
  "orderAccepted",
  "orderShipped",
  "orderConcluded",
  "orderCancelled",
  "categoryAddedToCart",
  "productAddedToCart",
  "productRemovedFromCart",
  "productOrdered",
  "contactReferredANewContact",
  "contactReferredExistingContact",
])
export type TriggerEventType = z.infer<typeof triggerEventTypes>
