const strings = {
  en: {
    newMessage: "New message",
    sharedLocation: "Shared a location",
    sentLink: "Sent a link",
    sentAttachment: "Sent an attachment",
    sentAttachments: (count: number) => `Sent ${count} attachments`,
    assignedConversation: "You were assigned a conversation",
  },
  vi: {
    newMessage: "Tin nhắn mới",
    sharedLocation: "Đã chia sẻ vị trí",
    sentLink: "Đã gửi một liên kết",
    sentAttachment: "Đã gửi một tệp đính kèm",
    sentAttachments: (count: number) => `Đã gửi ${count} tệp đính kèm`,
    assignedConversation: "Bạn đã được gán một cuộc trò chuyện",
  },
  ar: {
    newMessage: "رسالة جديدة",
    sharedLocation: "شارك موقعًا",
    sentLink: "أرسل رابطًا",
    sentAttachment: "أرسل مرفقًا",
    sentAttachments: (count: number) => `أرسل ${count} مرفقات`,
    assignedConversation: "تم تعيين محادثة لك",
  },
  da: {
    newMessage: "Ny besked",
    sharedLocation: "Delte en placering",
    sentLink: "Sendte et link",
    sentAttachment: "Sendte en vedhæftet fil",
    sentAttachments: (count: number) => `Sendte ${count} vedhæftede filer`,
    assignedConversation: "Du blev tildelt en samtale",
  },
  de: {
    newMessage: "Neue Nachricht",
    sharedLocation: "Hat einen Standort geteilt",
    sentLink: "Hat einen Link gesendet",
    sentAttachment: "Hat einen Anhang gesendet",
    sentAttachments: (count: number) => `Hat ${count} Anhänge gesendet`,
    assignedConversation: "Dir wurde eine Unterhaltung zugewiesen",
  },
  es: {
    newMessage: "Nuevo mensaje",
    sharedLocation: "Compartió una ubicación",
    sentLink: "Envió un enlace",
    sentAttachment: "Envió un archivo adjunto",
    sentAttachments: (count: number) => `Envió ${count} archivos adjuntos`,
    assignedConversation: "Se te asignó una conversación",
  },
  fi: {
    newMessage: "Uusi viesti",
    sharedLocation: "Jakoi sijainnin",
    sentLink: "Lähetti linkin",
    sentAttachment: "Lähetti liitteen",
    sentAttachments: (count: number) => `Lähetti ${count} liitettä`,
    assignedConversation: "Sinulle osoitettiin keskustelu",
  },
  fr: {
    newMessage: "Nouveau message",
    sharedLocation: "A partagé une position",
    sentLink: "A envoyé un lien",
    sentAttachment: "A envoyé une pièce jointe",
    sentAttachments: (count: number) => `A envoyé ${count} pièces jointes`,
    assignedConversation: "Une conversation vous a été assignée",
  },
  he: {
    newMessage: "הודעה חדשה",
    sharedLocation: "שיתף מיקום",
    sentLink: "שלח קישור",
    sentAttachment: "שלח קובץ מצורף",
    sentAttachments: (count: number) => `שלח ${count} קבצים מצורפים`,
    assignedConversation: "הוקצתה לך שיחה",
  },
  id: {
    newMessage: "Pesan baru",
    sharedLocation: "Membagikan lokasi",
    sentLink: "Mengirim tautan",
    sentAttachment: "Mengirim lampiran",
    sentAttachments: (count: number) => `Mengirim ${count} lampiran`,
    assignedConversation: "Anda ditugaskan sebuah percakapan",
  },
  it: {
    newMessage: "Nuovo messaggio",
    sharedLocation: "Ha condiviso una posizione",
    sentLink: "Ha inviato un link",
    sentAttachment: "Ha inviato un allegato",
    sentAttachments: (count: number) => `Ha inviato ${count} allegati`,
    assignedConversation: "Ti è stata assegnata una conversazione",
  },
  ja: {
    newMessage: "新しいメッセージ",
    sharedLocation: "位置情報を共有しました",
    sentLink: "リンクを送信しました",
    sentAttachment: "添付ファイルを送信しました",
    sentAttachments: (count: number) =>
      `${count}件の添付ファイルを送信しました`,
    assignedConversation: "会話が割り当てられました",
  },
  nl: {
    newMessage: "Nieuw bericht",
    sharedLocation: "Heeft een locatie gedeeld",
    sentLink: "Heeft een link verzonden",
    sentAttachment: "Heeft een bijlage verzonden",
    sentAttachments: (count: number) => `Heeft ${count} bijlagen verzonden`,
    assignedConversation: "Er is een gesprek aan je toegewezen",
  },
  "pt-BR": {
    newMessage: "Nova mensagem",
    sharedLocation: "Compartilhou uma localização",
    sentLink: "Enviou um link",
    sentAttachment: "Enviou um anexo",
    sentAttachments: (count: number) => `Enviou ${count} anexos`,
    assignedConversation: "Uma conversa foi atribuída a você",
  },
  "pt-PT": {
    newMessage: "Nova mensagem",
    sharedLocation: "Partilhou uma localização",
    sentLink: "Enviou uma ligação",
    sentAttachment: "Enviou um anexo",
    sentAttachments: (count: number) => `Enviou ${count} anexos`,
    assignedConversation: "Foi-lhe atribuída uma conversa",
  },
  ro: {
    newMessage: "Mesaj nou",
    sharedLocation: "A distribuit o locație",
    sentLink: "A trimis un link",
    sentAttachment: "A trimis un atașament",
    sentAttachments: (count: number) => `A trimis ${count} atașamente`,
    assignedConversation: "Ți-a fost atribuită o conversație",
  },
  sv: {
    newMessage: "Nytt meddelande",
    sharedLocation: "Delade en plats",
    sentLink: "Skickade en länk",
    sentAttachment: "Skickade en bilaga",
    sentAttachments: (count: number) => `Skickade ${count} bilagor`,
    assignedConversation: "Du tilldelades en konversation",
  },
  tr: {
    newMessage: "Yeni mesaj",
    sharedLocation: "Bir konum paylaştı",
    sentLink: "Bir bağlantı gönderdi",
    sentAttachment: "Bir ek gönderdi",
    sentAttachments: (count: number) => `${count} ek gönderdi`,
    assignedConversation: "Size bir görüşme atandı",
  },
  "zh-CN": {
    newMessage: "新消息",
    sharedLocation: "分享了位置",
    sentLink: "发送了一个链接",
    sentAttachment: "发送了一个附件",
    sentAttachments: (count: number) => `发送了 ${count} 个附件`,
    assignedConversation: "已为您分配一个对话",
  },
  "zh-TW": {
    newMessage: "新訊息",
    sharedLocation: "分享了位置",
    sentLink: "傳送了一個連結",
    sentAttachment: "傳送了一個附件",
    sentAttachments: (count: number) => `傳送了 ${count} 個附件`,
    assignedConversation: "已為您指派一個對話",
  },
} as const

type Locale = keyof typeof strings

const resolveLocale = (language: string | undefined): Locale =>
  language && language in strings ? (language as Locale) : "en"

export const t = (language: string | undefined) =>
  strings[resolveLocale(language)]
