// @vitest-environment node

/**
 * Repository inserts against the REAL column definitions.
 *
 * The bug this file exists for: `IntegrationMessenger.conversationStarters`
 * and friends are declared `jsonb().default(sql`[]`).notNull()` in the drizzle
 * schema, which makes them OPTIONAL in `$inferInsert` — but drizzle-kit drops a
 * `sql` default for a jsonb column when it serializes the snapshot, so the
 * migration created the column NOT NULL with **no database default**. Omitting
 * the key therefore made drizzle emit `DEFAULT`, and Postgres rejected the row.
 * Every unit test around those repositories mocked `../src/client`, so the only
 * thing that could have caught it is the database itself.
 *
 * These tests read `information_schema.columns` from a real Postgres and check
 * both directions of the insert contract, per repository:
 *
 *   - every column the database REQUIRES (NOT NULL, no column default, and not
 *     generated by drizzle at runtime via `$defaultFn`) is a key the repository
 *     always writes — even when the caller omits it;
 *   - every key the repository writes is a column the database actually has.
 *
 * No row is ever inserted: the repositories are called with a `tx` stub that
 * captures the object handed to `.values()`.
 *
 * The suite SKIPS itself unless `DATABASE_URL` points at a reachable database.
 * `@chatbotx.io/vitest-config`'s `setup-env` always defines `DATABASE_URL`
 * (a deliberately non-routable `127.0.0.1:1` sentinel), so "is it defined" is
 * not a usable signal — the port is. Run it against local docker Postgres with:
 *
 *     pnpm --filter @chatbotx.io/database test:db
 */

import { getTableColumns, getTableName } from "drizzle-orm"
import type { PgTable } from "drizzle-orm/pg-core"
import { Client } from "pg"
import { afterAll, beforeAll, describe, expect, test, vi } from "vitest"
import { integrationInstagramRepository } from "../../src/repositories/integration-instagram/repository"
import { integrationMessengerRepository } from "../../src/repositories/integration-messenger/repository"
import { integrationWhatsappRepository } from "../../src/repositories/integration-whatsapp/repository"
import { whatsappSignupSessionRepository } from "../../src/repositories/integration-whatsapp/signup-session"
import {
  inboxModel,
  integrationInstagramModel,
  integrationMessengerModel,
  integrationWhatsappModel,
  whatsappSignupSessionModel,
} from "../../src/schema"

/** The `setup-env` sentinel: a real database never listens on port 1. */
const NON_ROUTABLE_PORT = "1"

function realDatabaseUrl(): string | null {
  const url = process.env.DATABASE_URL
  if (!url) {
    return null
  }
  try {
    return new URL(url).port === NON_ROUTABLE_PORT ? null : url
  } catch {
    return null
  }
}

const databaseUrl = realDatabaseUrl()

type ColumnFact = {
  isNullable: boolean
  hasDatabaseDefault: boolean
}

type TableFacts = Map<string, ColumnFact>

const AUDITED_TABLES = [
  inboxModel,
  integrationInstagramModel,
  integrationMessengerModel,
  integrationWhatsappModel,
  whatsappSignupSessionModel,
] as unknown as PgTable[]

const facts = new Map<string, TableFacts>()

/**
 * Column names the database will reject an insert without: NOT NULL, no
 * column default, and no drizzle-side `$defaultFn` to fill them in.
 */
function requiredColumns(table: PgTable): string[] {
  const tableFacts = facts.get(getTableName(table))
  if (!tableFacts) {
    throw new Error(`no information_schema facts for ${getTableName(table)}`)
  }
  return Object.values(getTableColumns(table))
    .filter((column) => {
      const fact = tableFacts.get(column.name)
      return (
        fact !== undefined &&
        !(fact.isNullable || fact.hasDatabaseDefault) &&
        column.defaultFn === undefined
      )
    })
    .map((column) => column.name)
    .sort()
}

/** Maps the drizzle property keys a repository wrote to their column names. */
function writtenColumns(
  table: PgTable,
  written: Record<string, unknown>,
): string[] {
  const columns = getTableColumns(table)
  return Object.keys(written)
    .map((key) => columns[key]?.name ?? key)
    .sort()
}

/** A `tx` double that records `.values()` and resolves `.returning()` with one row. */
function capturingTx() {
  const values = vi.fn(() => ({
    returning: vi.fn().mockResolvedValue([{ id: "row-1" }]),
    onConflictDoUpdate: vi.fn(() => ({
      returning: vi.fn().mockResolvedValue([{ id: "row-1" }]),
    })),
  }))
  return {
    tx: { insert: vi.fn(() => ({ values })) } as never,
    written: () => values.mock.calls[0]?.[0] as Record<string, unknown>,
  }
}

describe.skipIf(!databaseUrl)(
  "repository inserts satisfy the real column definitions",
  () => {
    let client: Client

    beforeAll(async () => {
      client = new Client({ connectionString: databaseUrl as string })
      await client.connect()
      const { rows } = await client.query<{
        table_name: string
        column_name: string
        is_nullable: string
        column_default: string | null
      }>(
        `select table_name, column_name, is_nullable, column_default
           from information_schema.columns
          where table_schema = 'public' and table_name = any($1)`,
        [AUDITED_TABLES.map((table) => getTableName(table))],
      )
      for (const row of rows) {
        const tableFacts = facts.get(row.table_name) ?? new Map()
        tableFacts.set(row.column_name, {
          isNullable: row.is_nullable === "YES",
          hasDatabaseDefault: row.column_default !== null,
        })
        facts.set(row.table_name, tableFacts)
      }
    })

    afterAll(async () => {
      await client?.end()
    })

    test("every audited table was found in the database", () => {
      for (const table of AUDITED_TABLES) {
        expect(facts.get(getTableName(table))?.size ?? 0).toBeGreaterThan(0)
      }
    })

    /**
     * Each case calls the repository with ONLY the keys its input type makes
     * mandatory — exactly what a caller is free to pass — so a column the
     * repository leaves to a database default that does not exist shows up
     * here as a missing key rather than as a runtime NOT NULL violation.
     */
    const cases: {
      name: string
      table: PgTable
      run: (tx: never) => Promise<unknown>
    }[] = [
      {
        name: "integrationMessengerRepository.insert",
        table: integrationMessengerModel as unknown as PgTable,
        run: (tx) =>
          integrationMessengerRepository.insert(
            {
              id: "integration-1",
              workspaceId: "workspace-1",
              inboxId: "inbox-1",
              pageId: "page-1",
              auth: { tokens: { accessToken: "token" } },
              name: "My Page",
            },
            tx,
          ),
      },
      {
        name: "integrationInstagramRepository.insert",
        table: integrationInstagramModel as unknown as PgTable,
        run: (tx) =>
          integrationInstagramRepository.insert(
            {
              id: "integration-1",
              workspaceId: "workspace-1",
              inboxId: "inbox-1",
              igId: "ig-1",
              pageId: "page-1",
              auth: { tokens: { accessToken: "token" } },
              name: "My Account",
              username: "my_account",
            },
            tx,
          ),
      },
      {
        name: "integrationWhatsappRepository.upsertByInbox",
        table: integrationWhatsappModel as unknown as PgTable,
        run: (tx) =>
          integrationWhatsappRepository.upsertByInbox(
            {
              id: "integration-1",
              workspaceId: "workspace-1",
              inboxId: "inbox-1",
              auth: { tokens: { accessToken: "token" } },
              phoneNumberId: "phone-1",
              wabaId: "waba-1",
              businessId: "business-1",
              name: "My Number",
              isCoexist: false,
              platformType: "CLOUD_API",
            },
            tx,
          ),
      },
      {
        name: "whatsappSignupSessionRepository.createSignupSession",
        table: whatsappSignupSessionModel as unknown as PgTable,
        run: (tx) =>
          whatsappSignupSessionRepository.createSignupSession(
            {
              userId: "user-1",
              ownerId: "user-1",
              wabaId: "waba-1",
              businessId: "business-1",
              encryptedAccessToken: {
                iv: "iv",
                tag: "tag",
                content: "content",
              } as never,
              apiVersion: "v23.0",
              candidatePhoneNumberIds: ["phone-1"],
            },
            tx,
          ),
      },
    ]

    test.each(cases)("$name writes every column the database requires", async ({
      table,
      run,
    }) => {
      const { tx, written } = capturingTx()

      await run(tx)

      const writes = writtenColumns(table, written())
      for (const column of requiredColumns(table)) {
        expect(writes).toContain(column)
      }
    })

    test.each(cases)("$name writes only columns the database has", async ({
      table,
      run,
    }) => {
      const { tx, written } = capturingTx()

      await run(tx)

      const tableFacts = facts.get(getTableName(table)) as TableFacts
      for (const column of writtenColumns(table, written())) {
        expect(
          tableFacts.has(column) ? column : `${column} (missing in database)`,
        ).toBe(column)
      }
    })

    /**
     * `Inbox` rows are written by `inboxService.findOrCreate`
     * (`packages/business/src/inbox/service.ts`), which this package cannot
     * import — so pin the requirement instead. A new NOT NULL column without a
     * database default fails here, and the fix is to write it from that
     * service's `.values({ id: data.id ?? createId(), ...data })`.
     */
    test("the Inbox columns a connect must supply are still exactly these", () => {
      expect(requiredColumns(inboxModel as unknown as PgTable)).toEqual([
        "channel",
        "name",
        "sourceId",
        "workspaceId",
      ])
    })
  },
)
