import { z } from "zod"
import type { AiChatModelOption } from "./registry"

export const openrouterModels = z.enum([
  "openai/gpt-5.5-pro",
  "openai/gpt-5.5",
  "openai/gpt-5.4-pro",
  "openai/gpt-5.4",
  "openai/gpt-5.4-mini",
  "openai/gpt-5.4-nano",
  "openai/gpt-5.2-pro",
  "openai/gpt-5.2-chat",
  "openai/gpt-5.2",
  "openai/gpt-5.1",
  "openai/gpt-5.1-chat",
  "openai/gpt-5-pro",
  "openai/gpt-5",
  "openai/gpt-5-mini",
  "openai/gpt-5-nano",
  "openai/gpt-4.1",
  "openai/gpt-4.1-mini",
  "openai/gpt-4.1-nano",
  "openai/gpt-4o",
  "openai/gpt-4o-mini",
  "anthropic/claude-fable-5",
  "anthropic/claude-opus-4.8",
  "anthropic/claude-opus-4.8-fast",
  "anthropic/claude-opus-4.6",
  "anthropic/claude-sonnet-4.6",
  "anthropic/claude-opus-4.5",
  "anthropic/claude-sonnet-4.5",
  "anthropic/claude-haiku-4.5",
  "anthropic/claude-3-5-sonnet",
  "anthropic/claude-3-5-haiku",
  "google/gemini-3.5-flash",
  "google/gemini-3.1-pro-preview",
  "google/gemini-3.1-flash-lite",
  "google/gemini-3-flash-preview",
  "google/gemini-2.0-flash",
  "google/gemini-2.5-flash-lite",
  "google/gemini-2.5-flash",
  "google/gemini-2.5-pro",
  "google/gemini-2.5-pro-preview",
  "meta-llama/llama-4-maverick",
  "meta-llama/llama-4-scout",
  "meta-llama/llama-3.3-70b-instruct",
  "meta-llama/llama-3.2-90b-vision-instruct",
  "meta-llama/llama-3.2-11b-vision-instruct",
  "deepseek/deepseek-v4-pro",
  "deepseek/deepseek-v4-flash",
  "deepseek/deepseek-v3.2",
  "deepseek/deepseek-r1",
  "deepseek/deepseek-chat",
  "qwen/qwen3-max",
  "qwen/qwen3.7-max",
  "qwen/qwen3.7-plus",
  "qwen/qwen3-coder-plus",
  "qwen/qwen3-vl-32b-instruct",
  "qwen/qwen-2.5-72b-instruct",
  "mistralai/mistral-large-2512",
  "mistralai/mistral-medium-3-5",
  "mistralai/mistral-large",
  "x-ai/grok-4.20",
  "x-ai/grok-4.3",
])
export type OpenRouterModel = z.infer<typeof openrouterModels>

export const openrouterModelOptions: AiChatModelOption[] = [
  { label: "GPT-5.5 Pro", value: "openai/gpt-5.5-pro" },
  { label: "GPT-5.5", value: "openai/gpt-5.5" },
  { label: "GPT-5.4 Pro", value: "openai/gpt-5.4-pro" },
  { label: "GPT-5.4", value: "openai/gpt-5.4" },
  { label: "GPT-5.4 Mini", value: "openai/gpt-5.4-mini" },
  { label: "GPT-5.2 Pro", value: "openai/gpt-5.2-pro" },
  { label: "GPT-5.2", value: "openai/gpt-5.2" },
  { label: "GPT-5.1", value: "openai/gpt-5.1" },
  { label: "GPT-5", value: "openai/gpt-5" },
  { label: "GPT-5 Mini", value: "openai/gpt-5-mini" },
  { label: "GPT-4o", value: "openai/gpt-4o" },
  { label: "GPT-4o Mini", value: "openai/gpt-4o-mini" },
  { label: "Claude Fable 5", value: "anthropic/claude-fable-5" },
  { label: "Claude Opus 4.8", value: "anthropic/claude-opus-4.8" },
  { label: "Claude Opus 4.6", value: "anthropic/claude-opus-4.6" },
  { label: "Claude Sonnet 4.6", value: "anthropic/claude-sonnet-4.6" },
  { label: "Claude Sonnet 4.5", value: "anthropic/claude-sonnet-4.5" },
  { label: "Claude Haiku 4.5", value: "anthropic/claude-haiku-4.5" },
  { label: "Gemini 3.5 Flash", value: "google/gemini-3.5-flash" },
  { label: "Gemini 3.1 Pro Preview", value: "google/gemini-3.1-pro-preview" },
  { label: "Gemini 3.1 Flash Lite", value: "google/gemini-3.1-flash-lite" },
  { label: "Gemini 2.5 Flash", value: "google/gemini-2.5-flash" },
  { label: "Gemini 2.5 Flash Lite", value: "google/gemini-2.5-flash-lite" },
  { label: "Gemini 2.5 Pro", value: "google/gemini-2.5-pro" },
  { label: "Llama 4 Maverick", value: "meta-llama/llama-4-maverick" },
  { label: "Llama 4 Scout", value: "meta-llama/llama-4-scout" },
  { label: "Llama 3.3 70B", value: "meta-llama/llama-3.3-70b-instruct" },
  { label: "DeepSeek V4 Pro", value: "deepseek/deepseek-v4-pro" },
  { label: "DeepSeek V4 Flash", value: "deepseek/deepseek-v4-flash" },
  { label: "DeepSeek V3.2", value: "deepseek/deepseek-v3.2" },
  { label: "DeepSeek R1", value: "deepseek/deepseek-r1" },
  { label: "Qwen3 Max", value: "qwen/qwen3-max" },
  { label: "Qwen3.7 Max", value: "qwen/qwen3.7-max" },
  { label: "Qwen3 Coder Plus", value: "qwen/qwen3-coder-plus" },
  { label: "Mistral Large 3", value: "mistralai/mistral-large-2512" },
  { label: "Mistral Medium 3.5", value: "mistralai/mistral-medium-3-5" },
  { label: "Grok 4.20", value: "x-ai/grok-4.20" },
  { label: "Grok 4.3", value: "x-ai/grok-4.3" },
]

export const openrouterAnalyzeImageModelOptions: AiChatModelOption[] = [
  { label: "GPT-5.5 Pro", value: "openai/gpt-5.5-pro" },
  { label: "GPT-5.5", value: "openai/gpt-5.5" },
  { label: "GPT-5.4 Pro", value: "openai/gpt-5.4-pro" },
  { label: "GPT-5.4", value: "openai/gpt-5.4" },
  { label: "GPT-5.4 Mini", value: "openai/gpt-5.4-mini" },
  { label: "GPT-5.2 Pro", value: "openai/gpt-5.2-pro" },
  { label: "GPT-5.2", value: "openai/gpt-5.2" },
  { label: "GPT-5.1", value: "openai/gpt-5.1" },
  { label: "GPT-5", value: "openai/gpt-5" },
  { label: "GPT-4.1", value: "openai/gpt-4.1" },
  { label: "GPT-4o", value: "openai/gpt-4o" },
  { label: "GPT-4o Mini", value: "openai/gpt-4o-mini" },
  { label: "Claude Fable 5", value: "anthropic/claude-fable-5" },
  { label: "Claude Opus 4.8", value: "anthropic/claude-opus-4.8" },
  { label: "Claude Opus 4.6", value: "anthropic/claude-opus-4.6" },
  { label: "Claude Sonnet 4.6", value: "anthropic/claude-sonnet-4.6" },
  { label: "Claude Sonnet 4.5", value: "anthropic/claude-sonnet-4.5" },
  { label: "Claude Haiku 4.5", value: "anthropic/claude-haiku-4.5" },
  { label: "Gemini 3.5 Flash", value: "google/gemini-3.5-flash" },
  { label: "Gemini 3.1 Pro Preview", value: "google/gemini-3.1-pro-preview" },
  { label: "Gemini 3.1 Flash Lite", value: "google/gemini-3.1-flash-lite" },
  { label: "Gemini 2.5 Flash", value: "google/gemini-2.5-flash" },
  { label: "Gemini 2.5 Pro", value: "google/gemini-2.5-pro" },
  {
    label: "Llama 3.2 11B Vision",
    value: "meta-llama/llama-3.2-11b-vision-instruct",
  },
  { label: "Qwen3 VL 32B", value: "qwen/qwen3-vl-32b-instruct" },
]

export const openrouterExtractFileModelOptions: AiChatModelOption[] = [
  { label: "GPT-5.5 Pro", value: "openai/gpt-5.5-pro" },
  { label: "GPT-5.5", value: "openai/gpt-5.5" },
  { label: "GPT-5.4 Pro", value: "openai/gpt-5.4-pro" },
  { label: "GPT-5.4", value: "openai/gpt-5.4" },
  { label: "GPT-5.4 Mini", value: "openai/gpt-5.4-mini" },
  { label: "GPT-5.2 Pro", value: "openai/gpt-5.2-pro" },
  { label: "GPT-5.2", value: "openai/gpt-5.2" },
  { label: "GPT-5.1", value: "openai/gpt-5.1" },
  { label: "GPT-5", value: "openai/gpt-5" },
  { label: "GPT-4.1", value: "openai/gpt-4.1" },
  { label: "GPT-4o", value: "openai/gpt-4o" },
  { label: "GPT-4o Mini", value: "openai/gpt-4o-mini" },
  { label: "Claude Fable 5", value: "anthropic/claude-fable-5" },
  { label: "Claude Opus 4.8", value: "anthropic/claude-opus-4.8" },
  { label: "Claude Opus 4.6", value: "anthropic/claude-opus-4.6" },
  { label: "Claude Sonnet 4.6", value: "anthropic/claude-sonnet-4.6" },
  { label: "Claude Sonnet 4.5", value: "anthropic/claude-sonnet-4.5" },
  { label: "Claude Haiku 4.5", value: "anthropic/claude-haiku-4.5" },
  { label: "Gemini 3.5 Flash", value: "google/gemini-3.5-flash" },
  { label: "Gemini 3.1 Pro Preview", value: "google/gemini-3.1-pro-preview" },
  { label: "Gemini 3.1 Flash Lite", value: "google/gemini-3.1-flash-lite" },
  { label: "Gemini 2.5 Flash", value: "google/gemini-2.5-flash" },
  { label: "Gemini 2.5 Flash Lite", value: "google/gemini-2.5-flash-lite" },
  { label: "Gemini 2.5 Pro", value: "google/gemini-2.5-pro" },
]
