import { useState } from "react";
import { useLocation } from "wouter";
import { useMutation } from "@tanstack/react-query";
import { useAuth } from "@/context/AuthContext";
import RegisterForm, { type RegisterState } from "@/components/auth/RegisterForm";

const CODES=[{code:"+966",label:"🇸🇦 +966"},{code:"+967",label:"🇾🇪 +967"},{code:"+971",label:"🇦🇪 +971"},{code:"+965",label:"🇰🇼 +965"},{code:"+973",label:"🇧🇭 +973"},{code:"+974",label:"🇶🇦 +974"},{code:"+968",label:"🇴🇲 +968"},{code:"+962",label:"🇯🇴 +962"},{code:"+963",label:"🇸🇾 +963"},{code:"+961",label:"🇱🇧 +961"},{code:"+20",label:"🇪🇬 +20"},{code:"+1",label:"🇺🇸 +1"},{code:"+44",label:"🇬🇧 +44"}];
function phone(code:string,local:string){const digits=local.replace(/\D/g,"");return digits?`${code}${digits.replace(/^0+/,"")}`:""}

export default function RegisterPage(){
 const[,navigate]=useLocation();const{setAuth}=useAuth();const[form,setForm]=useState<RegisterState>({workspaceName:"",ownerName:"",email:"",password:"",phone:"",countryCode:"+966",website:""});const[showPassword,setShowPassword]=useState(false);const[error,setError]=useState("");const[googleLoading,setGoogleLoading]=useState(false);const clientId=(import.meta.env.VITE_GOOGLE_CLIENT_ID as string|undefined)??"";
 const mutation=useMutation({mutationFn:async(data:RegisterState)=>{const res=await fetch(`${import.meta.env.BASE_URL}api/auth/register`,{method:"POST",headers:{"Content-Type":"application/json"},credentials:"include",body:JSON.stringify({workspaceName:data.workspaceName,ownerName:data.ownerName,email:data.email,password:data.password,phone:phone(data.countryCode,data.phone)||undefined,website:data.website})});const json=await res.json();if(!res.ok)throw new Error(json.error??"خطأ في إنشاء الحساب");return json},onSuccess:data=>{setAuth({id:data.user.id,name:data.user.name,email:data.user.email,emailVerified:data.user.emailVerified,permissions:data.user.permissions??[],roleSlugs:data.user.roleSlugs??[]},data.workspaceId??data.workspace?.id??"",{onboardingCompleted:false});navigate("/onboarding")},onError:(e:Error)=>setError(e.message)});
 async function google(credential:string){setGoogleLoading(true);setError("");try{const res=await fetch(`${import.meta.env.BASE_URL}api/auth/google`,{method:"POST",headers:{"Content-Type":"application/json"},credentials:"include",body:JSON.stringify({credential})});const data=await res.json();if(!res.ok)throw new Error(data.error??"خطأ في تسجيل الدخول بـGoogle");setAuth({id:data.user.id,name:data.user.name,email:data.user.email,emailVerified:data.user.emailVerified,permissions:data.user.permissions??[],roleSlugs:data.user.roleSlugs??[]},data.workspaceId??"",{onboardingCompleted:!data.isNewUser});navigate(data.isNewUser?"/onboarding":"/dashboard")}catch(e){setError((e as Error).message)}finally{setGoogleLoading(false)}}
 function startGoogle(){if(!clientId){setError("تسجيل الدخول بـGoogle غير مهيأ بعد.");return}const init=()=>{window.google?.accounts.id.initialize({client_id:clientId,callback:(r:{credential:string})=>google(r.credential)});window.google?.accounts.id.prompt()};if(window.google){init();return}const s=document.createElement("script");s.src="https://accounts.google.com/gsi/client";s.async=true;s.defer=true;s.onload=init;document.head.appendChild(s)}
 return <RegisterForm form={form} setForm={setForm} error={error} pending={mutation.isPending} googleLoading={googleLoading} googleEnabled={!!clientId} showPassword={showPassword} setShowPassword={setShowPassword} onGoogle={startGoogle} onSubmit={e=>{e.preventDefault();setError("");mutation.mutate(form)}} codes={CODES}/>;
}
