import { Building2, Eye, EyeOff, LockKeyhole, Mail, Phone, Sparkles, UserRound } from "lucide-react";
import { cn } from "@/lib/utils";
import { AuthLayout, GoogleIcon } from "@/components/auth/WesalAuthLayout";

export type RegisterState={workspaceName:string;ownerName:string;email:string;password:string;phone:string;countryCode:string;website:string};
type Props={form:RegisterState;setForm:(value:RegisterState)=>void;error:string;pending:boolean;googleLoading:boolean;googleEnabled:boolean;showPassword:boolean;setShowPassword:(value:boolean)=>void;onGoogle:()=>void;onSubmit:(e:React.FormEvent)=>void;codes:{code:string;label:string}[]};

function PasswordChecks({password}:{password:string}){if(!password)return null;const checks=[["8 أحرف",password.length>=8],["حرف إنجليزي",/[a-zA-Z]/.test(password)],["رقم",/\d/.test(password)]] as const;return <div className="mt-2 grid grid-cols-3 gap-1">{checks.map(([label,ok])=><span key={label} className={cn("rounded-lg border px-2 py-1.5 text-center text-[9px] font-bold",ok?"border-emerald-400/25 bg-emerald-500/10 text-emerald-300":"auth-mute border-[var(--auth-line)]")}>{ok?"✓":"○"} {label}</span>)}</div>}

export default function RegisterForm(p:Props){const strong=p.form.password.length>=8&&/[a-zA-Z]/.test(p.form.password)&&/\d/.test(p.form.password);const set=(key:keyof RegisterState,value:string)=>p.setForm({...p.form,[key]:value});return <AuthLayout title="ابدأ فريق خدمة عملاء ذكيًا خلال دقائق" subtitle="أنشئ مساحة عملك واربط قنواتك، ثم دع وكلاء وصال ون يردّون ويقودون المحادثات بينما يبقى فريقك مسيطرًا." bullets={["تجربة مجانية دون بطاقة دفع","إعداد بسيط لا يحتاج خبرة تقنية","عزل كامل وآمن لبيانات كل مساحة عمل"]}>
  <div className="mb-5"><div className="mb-3 inline-flex items-center gap-2 rounded-full border px-3 py-1.5 text-[11px] font-bold" style={{borderColor:"var(--auth-line)",color:"var(--auth-secondary)",background:"rgba(34,211,238,.08)"}}><Sparkles className="h-3.5 w-3.5"/>ابدأ مجانًا</div><h1 className="text-3xl font-black">أنشئ مساحة عملك</h1><p className="auth-soft mt-2 text-sm leading-6">أدخل بياناتك الأساسية وسنجهز لك وصال ون مباشرة.</p></div>
  <div className="auth-card rounded-[24px] p-5 sm:p-7">
    {p.error&&<div className="mb-4 rounded-xl border border-red-400/25 bg-red-500/10 p-3 text-center text-sm text-red-300">{p.error}</div>}
    {p.googleEnabled&&<><button type="button" onClick={p.onGoogle} disabled={p.googleLoading||p.pending} className="auth-secondary-button flex h-12 w-full items-center justify-center gap-2 rounded-xl text-sm font-bold disabled:opacity-60">{p.googleLoading?<span className="h-4 w-4 animate-spin rounded-full border-2 border-blue-500 border-t-transparent"/>:<GoogleIcon/>}المتابعة باستخدام Google</button><div className="auth-mute my-4 flex items-center gap-3 text-[10px]"><div className="auth-divider h-px flex-1"/>أو أدخل بياناتك<div className="auth-divider h-px flex-1"/></div></>}
    <form onSubmit={p.onSubmit} className="space-y-3.5">
      <input type="text" name="website" value={p.form.website} onChange={e=>set("website",e.target.value)} className="hidden" tabIndex={-1} autoComplete="off" aria-hidden="true"/>
      <div className="grid gap-3 sm:grid-cols-2"><Field id="reg-workspace" label="اسم الشركة / المساحة" icon={<Building2/>}><input id="reg-workspace" value={p.form.workspaceName} onChange={e=>set("workspaceName",e.target.value)} className="auth-input ps-10 text-sm" placeholder="شركتي للتجارة" autoComplete="organization" required/></Field><Field id="reg-name" label="اسمك" icon={<UserRound/>}><input id="reg-name" value={p.form.ownerName} onChange={e=>set("ownerName",e.target.value)} className="auth-input ps-10 text-sm" placeholder="محمد أحمد" autoComplete="name" required/></Field></div>
      <Field id="reg-email" label="البريد الإلكتروني" icon={<Mail/>}><input id="reg-email" type="email" value={p.form.email} onChange={e=>set("email",e.target.value)} className="auth-input ps-10 text-sm" placeholder="example@company.com" autoComplete="email" required dir="ltr"/></Field>
      <div><label htmlFor="reg-phone" className="mb-1.5 block text-xs font-bold">رقم الجوال <span className="auth-mute font-normal">(اختياري)</span></label><div className="flex gap-2" dir="ltr"><select value={p.form.countryCode} onChange={e=>set("countryCode",e.target.value)} className="auth-select w-[112px] shrink-0 text-sm">{p.codes.map(c=><option key={c.code} value={c.code}>{c.label}</option>)}</select><div className="relative min-w-0 flex-1"><Phone className="auth-mute absolute start-3 top-1/2 h-4 w-4 -translate-y-1/2"/><input id="reg-phone" type="tel" value={p.form.phone} onChange={e=>set("phone",e.target.value)} className="auth-input ps-10 text-sm" placeholder="5xxxxxxxx" autoComplete="tel-national"/></div></div></div>
      <div><label htmlFor="reg-password" className="mb-1.5 block text-xs font-bold">كلمة المرور</label><div className="relative"><LockKeyhole className="auth-mute absolute start-3 top-1/2 h-4 w-4 -translate-y-1/2"/><input id="reg-password" type={p.showPassword?"text":"password"} value={p.form.password} onChange={e=>set("password",e.target.value)} className="auth-input px-10 text-sm" placeholder="••••••••" autoComplete="new-password" required minLength={8} dir="ltr"/><button type="button" onClick={()=>p.setShowPassword(!p.showPassword)} className="auth-mute absolute end-3 top-1/2 -translate-y-1/2 p-1">{p.showPassword?<EyeOff className="h-4 w-4"/>:<Eye className="h-4 w-4"/>}</button></div><PasswordChecks password={p.form.password}/></div>
      <button type="submit" disabled={p.pending||!strong} className={cn("auth-primary h-12 w-full rounded-xl text-sm font-black",(p.pending||!strong)&&"cursor-not-allowed opacity-60")}>{p.pending?"جار إنشاء الحساب...":"إنشاء الحساب والبدء"}</button>
    </form>
    <p className="auth-mute mt-4 text-center text-[10px]">بإنشاء الحساب توافق على <a href="/terms" className="auth-link font-bold">الشروط</a> و<a href="/privacy" className="auth-link font-bold">الخصوصية</a>.</p><p className="auth-soft mt-3 text-center text-sm">لديك حساب؟ <a href="/login" className="auth-link font-black">تسجيل الدخول</a></p>
  </div>
</AuthLayout>}

function Field({id,label,icon,children}:{id:string;label:string;icon:React.ReactElement;children:React.ReactNode}){return <div><label htmlFor={id} className="mb-1.5 block text-xs font-bold">{label}</label><div className="relative"><span className="auth-mute absolute start-3 top-1/2 [&>svg]:h-4 [&>svg]:w-4 -translate-y-1/2">{icon}</span>{children}</div></div>}
